version: '3'

services:
  laravelapp:
    container_name: laravelapp
    image: francescoxx/laravelapp:1.0.0
    build: . 
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=groenevingers_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
