version: '3'

services:
  laravelapp:
    container_name: laravelapp
    image: sj0rs1/groenevingers_api:latest
    build: . 
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - laravel

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=groenevingers_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
    driver: bridge
